[package]
name = "qrsplit_contracts"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.12.2"

[dev-dependencies]
snforge_std = "0.49.0"
assert_macros = "2.12.2"

[[target.starknet-contract]]
sierra = true
casm = true

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]
