[package]
name = "qrsplit_contracts"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = "2.4.0"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.12.0" }

[[target.starknet-contract]]
sierra = true

[tool.snforge]
# exit_first = true